name: Build & Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [amd64]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.2'
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Build
        env:
          GOARCH: ${{ matrix.arch }}
        run: |
          go build -o bin/app ./cmd/client
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ runner.os }}-${{ matrix.arch }}
          path: bin/app