name: Build & Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [amd64]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.2'
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Build
        env:
          GOARCH: ${{ matrix.arch }}
        run: |
          go build -o bin/client ./cmd/client
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: client-${{ runner.os }}-${{ matrix.arch }}
          path: bin/client
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Get Release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARCH: ${{ matrix.arch }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: dist/client-${{ runner.os }}-${{ env.ARCH }}
          asset_name: client-${{ runner.os }}-${{ env.ARCH }}
          asset_content_type: application/octet-stream